apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: project-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: web-pv
  resources:
    requests:
      storage: 1Gi
